version: '3.8'

services:

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: CatalogDb
        volumes:
            - mongodb_data:/data/db
            - mongodb_config:/data/configdb
        networks:
            - catalog-network

    # add redis
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - catalog-network
    postgresdb:
        image: postgres:15-alpine
        restart: unless-stopped
        env_file:
            - .env.dev
        volumes:
            - commerce_postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - discount-network
      
    pgadmin:
        image: dpage/pgadmin4:7
        restart: unless-stopped
        env_file:
            - .env.dev
        environment:
            - PGADMIN_CONFIG_SERVER_MODE=False
            - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        ports:
            - "5051:80"
        volumes:
            - commerce_pgadmin_data:/var/lib/pgadmin
            - ./pgadmin-servers.json:/pgadmin4/servers.json # Mount the servers.json file, auto configure servers
        depends_on:
            postgresdb:
                condition: service_started
        networks:
            - discount-network

volumes:
    mongodb_data:
        driver: local
    mongodb_config:
        driver: local
    commerce_postgres_data:
        driver: local
    commerce_pgadmin_data:
        driver: local

networks:
    catalog-network:
        driver: bridge
    discount-network:
        driver: bridge
